"""Report writer: markdown (human) + JSON (machine). Markdown is the
evidence artifact the human relays to the security contact."""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from .models import Report, VerdictStatus

BANNER = {
    VerdictStatus.CLEAR: "CLEAR — no sanctions or on-chain risk hits",
    VerdictStatus.STOP_HIT: "STOP — confirmed hit. Do not sign.",
    VerdictStatus.STOP_INCONCLUSIVE: "STOP — inconclusive screen. Do not sign.",
}


def _md_table(rows: list[list[str]], header: list[str]) -> str:
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def render_markdown(report: Report, checklist_ref: str) -> str:
    v = report.verdict
    req = report.request
    lines = [
        f"# Recipient Screening Report — {BANNER[v.status]}",
        "",
        f"**Verdict:** `{v.status.value}`  ",
        f"**Screened at (UTC):** {report.screened_at}  ",
        f"**Basis:** {checklist_ref}",
        "",
        "## Request",
        "",
        _md_table(
            [["Address", f"`{req.address}`"],
             ["Chain", req.chain],
             ["Entity name (as claimed)", req.entity_name or "—"],
             ["Context", req.context or "—"]],
            ["Field", "Value"]),
        "",
        "## Checks run",
        "",
    ]
    rows = []
    for c in report.checks:
        status = ("OK" if c.ok else
                  ("NOT RUN" if not c.ran else "INCONCLUSIVE"))
        prov = c.provenance
        prov_str = (f"{prov.source_id} · fetched {prov.fetched_at} · "
                    f"sha256 {prov.sha256[:12]}…" if prov else "—")
        rows.append([c.check_id, status, str(len(c.hits)), prov_str,
                     c.notes or c.inconclusive_reason or ""])
    lines.append(_md_table(rows, ["Check", "Result", "Hits", "Provenance",
                                  "Notes"]))
    lines += ["", "## Findings", ""]
    any_hits = False
    for c in report.checks:
        for h in c.hits:
            any_hits = True
            lines += [
                f"### {h.kind.value} — {h.source_id}",
                "",
                f"- **Matched value:** `{h.matched_value}`",
                f"- **List entry:** {h.entry_name} (ref `{h.entry_reference}`)",
                f"- **Detail:** {h.detail}",
            ]
            if h.verbatim:
                lines.append("- **Verbatim source fields:**")
                lines.append("  ```json")
                lines.append("  " + json.dumps(h.verbatim, indent=2,
                                               default=str).replace(
                                                   "\n", "\n  "))
                lines.append("  ```")
            lines.append("")
    if not any_hits:
        lines.append("No findings.")
        lines.append("")
    lines += [
        "## Verdict and required action",
        "",
        f"**{v.status.value}** — " + "; ".join(v.reasons),
        "",
        f"> {v.required_action}",
        "",
        f"**Escalation contact:** {v.escalate_to}",
        "",
        "## Provenance appendix",
        "",
    ]
    prov_rows = []
    for c in report.checks:
        if c.provenance:
            p = c.provenance
            prov_rows.append([p.source_id, p.url[:60], p.fetched_at,
                              f"`{p.sha256[:16]}…`", str(p.bytes),
                              p.detail or "—"])
    if prov_rows:
        lines.append(_md_table(prov_rows,
                               ["Source", "URL", "Fetched (UTC)", "SHA-256",
                                "Bytes", "Detail"]))
    else:
        lines.append("No external sources (offline checks only).")
    lines += [
        "",
        "---",
        "_Generated by recipient-screening (deterministic engine — no model "
        "judgment in the verdict). Screening covers item 9 only; the other "
        "17 checklist items still apply. Not legal advice._",
    ]
    return "\n".join(lines)


def write_reports(report: Report, reports_dir: Path,
                  checklist_ref: str) -> tuple[Path, Path]:
    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    stamp = datetime.now(timezone.utc).strftime("%H%M%S")
    short = report.request.address[:10]
    out_dir = reports_dir / day
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"{stamp}_{short}.md"
    json_path = out_dir / f"{stamp}_{short}.json"
    md_path.write_text(render_markdown(report, checklist_ref))
    payload = asdict(report)
    json_path.write_text(json.dumps(payload, indent=2, default=str))
    return md_path, json_path
